export const SCRUTINY_REFERENCE = {
  wrongVowelGroup: [
    { word: "主人公になれぬ", issue: "romaji 'shujinkouninarenai' → 'shujinkouninarenu' (ぬ=nu not nai)", fix: "romaji correction changed group" },
    { word: "お飾りクール", issue: "romaji 'okazarikooru' → 'okazarikuuru' (く=ku not ko, ー extends vowel)", fix: "romaji correction changed group" },
    { word: "何の爪痕も", issue: "romaji 'nannotsumeatomou' → 'nannotsumeatomo' (も=mo not mou)", fix: "romaji correction changed group" },
    { word: "顔が公害", issue: "romaji 'kaogakouga' → 'kaogakougai' (がい=gai, final い missing)", fix: "romaji correction changed group" },
    { word: "ヌルテカ", issue: "romaji 'nuruteruka' → 'nuruteka' (てか=teka, extra 'ru' inserted)", fix: "romaji correction changed group" },
    { word: "存在価値なし", issue: "reading 'なす' → 'なし', romaji 'sonzaikachinasu' → 'sonzaikachinashi'", fix: "reading+romaji correction changed group" },
    { word: "合理デブ", issue: "romaji 'gouridehabu' → 'gouridebu' (デブ=debu, extra 'ha' inserted)", fix: "romaji correction changed group" },
    { word: "喋るなカス", issue: "romaji 'shaberunakas' → 'shaberunakasu' (カス=kasu, final 'u' missing)", fix: "romaji correction changed group" },
    { word: "喋るな口塞げ", issue: "romaji correct but user judged vowel group ae as unsuitable", fix: "moved to NG" },
  ],
  duplicateRhymeEndings: [
    { kept: "便器がお似合い", deleted: ["沈黙がお似合い"], sharedEnding: "お似合い" },
    { kept: "邪魔な存在", deleted: ["ゲロ以下の存在", "唾棄すべき存在"], sharedEnding: "存在" },
    { kept: "無価値", deleted: ["生きてる価値"], sharedEnding: "価値" },
    { kept: "給料泥棒", deleted: ["視聴率泥棒"], sharedEnding: "泥棒" },
    { kept: "死臭漂う", deleted: ["悪臭が漂う"], sharedEnding: "漂う" },
    { kept: "老害まっしぐら", deleted: ["孤独死まっしぐら"], sharedEnding: "まっしぐら" },
    { kept: "役立たずだ", deleted: ["役立たずが"], sharedEnding: "役立たず" },
    { kept: "人間失格", deleted: ["芸人失格"], sharedEnding: "失格" },
    { kept: "引退が遅い", deleted: ["動きが遅い"], sharedEnding: "遅い" },
    { kept: "面汚し", deleted: ["陰気な面汚し"], sharedEnding: "面汚し" },
  ],
  incompleteWords: [
    { word: "生きる価値無", reading: "いきるかちな", issue: "word truncated, not a complete sentence" },
  ],
  commonRomajiMistakes: [
    "ぬ→nai (should be nu)",
    "も→mou (should be mo)",
    "がい→ga (should be gai, final い missing)",
    "く+ー→ko+o (should be ku+u, ー extends previous vowel)",
    "デブ→dehabu (should be debu, extra syllable inserted)",
    "カス→kas (should be kasu, final vowel missing)",
    "てか→teruka (should be teka, extra syllable inserted)",
    "なし→nasu (should be nashi, し≠す confusion)",
  ],
  duplicateDetectionGaps: [
    "漢字が同じで表記が違う (e.g. ひらがな vs カタカナ vs 漢字で同じ言葉)",
    "漢字が一緒なのにフリガナが間違っていて同一認識できない",
    "同じ語幹+違う助詞 (e.g. 役立たずだ vs 役立たずが)",
    "短い語が長い語の一部 (e.g. 面汚し ⊂ 陰気な面汚し)",
  ],
};
